### ISSUE TITLE
2023 POE coordinator not working after changing firmware?

### ISSUE THREAD

**Issue by ClintElliotMalcolm** [tube0013/tube_gateways#182]
I received the tubeszb-cc2652p7-poe-2023 coordinator recently and for a time things were looking mostly good with my zigbee2mqtt setup. I kept having dropped connections and also occasionally had the `SRSP - SYS - ping after 6000ms` error. I decided yesterday to update the firmware and changing the IEEE address to be the same as my old coordinator. However this made it only get the  `SRSP - SYS - ping after 6000ms` error. I've tried a lot of things and haven't been able to make any progress. 

Things I tried to fix:
* Power cycles on Zigbee2Mqtt and the coordinator
* Updating the ESPHome Firmware
* Changing the ESPHome Firmware to have a static IP
* Using the zstack firmware 20221226, 20230507, 20231111, 20231112
* Changing the IEEE address back to the same as the primary

Basic command used.
```
python3 cc2538-bsl.py -evw -i {IEEE} -p socket://{IP}:6638 CC1352P2_CC2652P_launchpad_coordinator_{date}.hex
```

Tried the tube addon to change the firmware and that hasn't worked either. 

No zigpy commands have been able to work. They error out while trying to skip bootloader?
```
Traceback (most recent call last):
  File "/home/clint/zigbee-stuff/venv/lib/python3.9/site-packages/zigpy_znp/api.py", line 694, in _skip_bootloader
    result = await responses.get()
  File "/usr/lib/python3.9/asyncio/queues.py", line 166, in get
    await getter
asyncio.exceptions.CancelledError
```

I don't see any useful logs in the ESPHome dash even when turing on very verbose.

Anything you could suggest I'd really appreciate.

**Comment by tube0013** [comment]
When you reflashed ESPHome was it over OTA through ESPHome or via usb? 

If not usb, please try that - I typically suggest this first when that error surfaces.

**Comment by ClintElliotMalcolm** [comment]
I tried USB initially and then OTA once I switched to static ip. I'll try USB again and then see what happens.

**Comment by ClintElliotMalcolm** [comment]
Yeah another USB flash didn't change anything

**Comment by tube0013** [comment]
if you leave z2m shutdown, and boot up the esp does it show serial connected - ie is something else attempting to use the serial too?

if you were able to flash the serial it means the serial stream is working. 

can you try my zigpy-cli tools addon and see if you can run an energy scan, or do a backup

thanks.

**Comment by ClintElliotMalcolm** [comment]
Unfortunately none of that works, except flashing by serial... I'll paste in the config and logs.

Nothing connected to serial
![image](https://github.com/tube0013/tube_gateways/assets/2604394/8a28e182-f226-4f88-9bd4-afe18b709edf)
![image](https://github.com/tube0013/tube_gateways/assets/2604394/b693e31f-caf0-460a-8081-0958f4b09712)

zigpy-cli addon energy scan config
![image](https://github.com/tube0013/tube_gateways/assets/2604394/5a65cb22-2d6e-45ef-91a7-987830eba0ce)

Doesn't work:
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service banner: starting

-----------------------------------------------------------
 Add-on: TubesZB Zigpy-CLI Tools
 TubesZB Zigpy-CLI Toolsadd-on
-----------------------------------------------------------
 Add-on version: 0.2.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.4  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2024.1.4
 Home Assistant Supervisor: 2023.12.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service banner successfully started
s6-rc: info: service zigpy-cli: starting
[15:56:52] INFO: Directoty Exists
[15:56:55] INFO: Running zigpy - info on socket://192.168.1.251:6638
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/zigpy_znp/api.py", line 694, in _skip_bootloader
    result = await responses.get()
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/queues.py", line 158, in get
    await getter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/zigpy", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/decorators.py", line 45, in new_func
    return f(get_current_context().obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/zigpy_cli/cli.py", line 20, in inner
    return loop.run_until_complete(cmd(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/zigpy_cli/radio.py", line 85, in info
    await app.connect()
  File "/usr/local/lib/python3.11/site-packages/zigpy_znp/zigbee/application.py", line 103, in connect
    await znp.connect()
  File "/usr/local/lib/python3.11/site-packages/zigpy_znp/api.py", line 736, in connect
    self.capabilities = (await self._skip_bootloader()).Capabilities
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/zigpy_znp/api.py", line 693, in _skip_bootloader
    async with async_timeout.timeout(CONNECT_PROBE_TIMEOUT):
  File "/usr/local/lib/python3.11/site-packages/async_timeout/__init__.py", line 141, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.11/site-packages/async_timeout/__init__.py", line 228, in _do_exit
    raise asyncio.TimeoutError
TimeoutError
[15:57:08] INFO: zigpy-cli-up script exited with code 1
s6-rc: warning: unable to start service zigpy-cli: command exited 1
s6-rc: info: service banner: stopping
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service banner successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```
While it was connected the esphome dash did show it connected before the exception is thrown. 
```
15:56:58 | [D] | [stream_server:081] | New client connected from 192.168.1.99
15:56:58 | [D] | [binary_sensor:036] | 'TubesZB Serial Connected': Sending state ON
15:57:08 | [D] | [stream_server:163] | Client 192.168.1.99 disconnected
15:57:08 | [D] | [binary_sensor:036] | 'TubesZB Serial Connected': Sending state OFF
```

Additionally trying info and backup give it the exact same error.

Flashing through TubesZB TI CC2652 FW Flasher with `https://github.com/Koenkk/Z-Stack-firmware/raw/Z-Stack_3.x.0_coordinator_20230507/coordinator/Z-Stack_3.x.0/bin/CC1352P2_CC2652P_launchpad_coordinator_20230507.zip`
![image](https://github.com/tube0013/tube_gateways/assets/2604394/41e8f3c0-4b59-418f-8505-dfe58389b12a)

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service banner: starting

-----------------------------------------------------------
 Add-on: TubesZB TI CC2652 FW Flasher
 TubesZB TI CC2652 firmware flasher add-on
-----------------------------------------------------------
 Add-on version: 0.2.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.4  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2024.1.4
 Home Assistant Supervisor: 2023.12.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service banner successfully started
s6-rc: info: service cc2652-flasher: starting
[16:00:04] INFO: Triggering Bootloader mode on 192.168.1.251
[16:00:13] INFO: Starting cc2652 flasher with socket://192.168.1.251:6638
Setting filename to /root/firmware.hex
Opening port socket://192.168.1.251:6638, baud 500000
Reading data from /root/firmware.hex
Your firmware looks like an Intel Hex file
Connecting to target...
pg_rev = 1, protocols = f, wafer_id = 0xbb77
CC135x PG1.1 (7x7mm): 704KB Flash, 20KB SRAM, CCFG.BL_CONFIG at 0x000AFFD8
Primary IEEE Address: 00:12:4B:00:2A:7B:4F:6D
    Performing mass erase
Erasing all main bank flash sectors
    Erase done
Writing 360448 bytes starting at address 0x00000000
 Write 248 bytes at 0x00000000
... writing bytes ...
Write 104 bytes at 0x00057F98
    Write done                                
Verifying by comparing CRC32 calculations.
    Verified (match: 0xe83aa727)
[16:06:24] INFO: cc2652-flasher-up script exited with code 0
s6-rc: info: service cc2652-flasher successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service cc2652-flasher: stopping
s6-rc: info: service cc2652-flasher successfully stopped
s6-rc: info: service banner: stopping
s6-rc: info: service banner successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

ESPHome dash logs:
```
16:00:04 | [D] | [button:010] | 'Trigger Zigbee Module Bootloader' Pressed.
16:00:04 | [D] | [switch:012] | 'Zigbee Module Bootloader Pin' Turning ON.
16:00:04 | [D] | [switch:055] | 'Zigbee Module Bootloader Pin': Sending state ON
16:00:05 | [D] | [switch:012] | 'zRST_gpio' Turning ON.
16:00:05 | [D] | [switch:055] | 'zRST_gpio': Sending state ON
16:00:06 | [D] | [switch:016] | 'zRST_gpio' Turning OFF.
16:00:06 | [D] | [switch:055] | 'zRST_gpio': Sending state OFF
16:00:06 | [D] | [main:555] | Delaying ~10 seconds for cc2652p2 to settle
16:00:14 | [D] | [stream_server:081] | New client connected from 192.168.1.99
16:00:14 | [D] | [binary_sensor:036] | 'TubesZB Serial Connected': Sending state ON
16:00:17 | [D] | [switch:016] | 'Zigbee Module Bootloader Pin' Turning OFF.
16:00:17 | [D] | [switch:055] | 'Zigbee Module Bootloader Pin': Sending state OFF
16:00:17 | [D] | [main:563] | Please try update with cc2538-bsl tool now
16:00:17 | [D] | [main:566] | cc-bsl usage: cc2538-bsl.py -p socket://ip-of-gw:6638 -evw firmware.hex
16:06:24 | [D] | [stream_server:163] | Client 192.168.1.99 disconnected
16:06:24 | [D] | [binary_sensor:036] | 'TubesZB Serial Connected': Sending state OFF
```

**Comment by ClintElliotMalcolm** [comment]
That would make a lot of sense. I'll flash that and get back to you.

**Comment by ClintElliotMalcolm** [comment]
Yup that was it. Thanks for replying so promptly. Things seems to be working again.

**Comment by tube0013** [comment]
Awesome. I'll add some docs to make sure the firmware types are clear. I list the version the units ship with in the little insert included with the package, but want it to be more obvious. Thanks for your patience.
